//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.ws/")]
    public partial class CreateBookException
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.ws/")]
    public partial class createBookRsp
    {
        
        private long idField;
        
        private bool idFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.ws/")]
    public partial class tag
    {
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string tagNameField;
        
        private book[] bookField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string tagName
        {
            get
            {
                return this.tagNameField;
            }
            set
            {
                this.tagNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("book", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public book[] book
        {
            get
            {
                return this.bookField;
            }
            set
            {
                this.bookField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.ws/")]
    public partial class book
    {
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string isbnField;
        
        private string titleField;
        
        private string authorField;
        
        private tag[] tagsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string isbn
        {
            get
            {
                return this.isbnField;
            }
            set
            {
                this.isbnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string author
        {
            get
            {
                return this.authorField;
            }
            set
            {
                this.authorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public tag[] tags
        {
            get
            {
                return this.tagsField;
            }
            set
            {
                this.tagsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.ws/")]
    public partial class createBookReq
    {
        
        private book bookField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public book book
        {
            get
            {
                return this.bookField;
            }
            set
            {
                this.bookField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.ws/")]
    public partial class BookNotFoundException
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://soap.ws/", ConfigurationName="ServiceReference1.BookWebService")]
    public interface BookWebService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.ws/BookWebService/createBookRequest", ReplyAction="http://soap.ws/BookWebService/createBookResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.CreateBookException), Action="http://soap.ws/BookWebService/createBook/Fault/CreateBookException", Name="CreateBookException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tag[]))]
        System.Threading.Tasks.Task<ServiceReference1.createBookResponse> createBookAsync(ServiceReference1.createBookRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.ws/BookWebService/deleteBookRequest", ReplyAction="http://soap.ws/BookWebService/deleteBookResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.BookNotFoundException), Action="http://soap.ws/BookWebService/deleteBook/Fault/BookNotFoundException", Name="BookNotFoundException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tag[]))]
        System.Threading.Tasks.Task<ServiceReference1.deleteBookResponse> deleteBookAsync(ServiceReference1.deleteBookRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.ws/BookWebService/retrieveBookRequest", ReplyAction="http://soap.ws/BookWebService/retrieveBookResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.BookNotFoundException), Action="http://soap.ws/BookWebService/retrieveBook/Fault/BookNotFoundException", Name="BookNotFoundException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tag[]))]
        System.Threading.Tasks.Task<ServiceReference1.retrieveBookResponse> retrieveBookAsync(ServiceReference1.retrieveBookRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.ws/BookWebService/retrieveAllBooksRequest", ReplyAction="http://soap.ws/BookWebService/retrieveAllBooksResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tag[]))]
        System.Threading.Tasks.Task<ServiceReference1.retrieveAllBooksResponse> retrieveAllBooksAsync(ServiceReference1.retrieveAllBooksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.ws/BookWebService/updateBookRequest", ReplyAction="http://soap.ws/BookWebService/updateBookResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.BookNotFoundException), Action="http://soap.ws/BookWebService/updateBook/Fault/BookNotFoundException", Name="BookNotFoundException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tag[]))]
        System.Threading.Tasks.Task<ServiceReference1.updateBookResponse> updateBookAsync(ServiceReference1.updateBookRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createBook", WrapperNamespace="http://soap.ws/", IsWrapped=true)]
    public partial class createBookRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.createBookReq arg0;
        
        public createBookRequest()
        {
        }
        
        public createBookRequest(ServiceReference1.createBookReq arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createBookResponse", WrapperNamespace="http://soap.ws/", IsWrapped=true)]
    public partial class createBookResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.createBookRsp @return;
        
        public createBookResponse()
        {
        }
        
        public createBookResponse(ServiceReference1.createBookRsp @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteBook", WrapperNamespace="http://soap.ws/", IsWrapped=true)]
    public partial class deleteBookRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public deleteBookRequest()
        {
        }
        
        public deleteBookRequest(long arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteBookResponse", WrapperNamespace="http://soap.ws/", IsWrapped=true)]
    public partial class deleteBookResponse
    {
        
        public deleteBookResponse()
        {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.ws/")]
    public partial class retrieveBookRsp
    {
        
        private book bookField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public book book
        {
            get
            {
                return this.bookField;
            }
            set
            {
                this.bookField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retrieveBook", WrapperNamespace="http://soap.ws/", IsWrapped=true)]
    public partial class retrieveBookRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public retrieveBookRequest()
        {
        }
        
        public retrieveBookRequest(long arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retrieveBookResponse", WrapperNamespace="http://soap.ws/", IsWrapped=true)]
    public partial class retrieveBookResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.retrieveBookRsp @return;
        
        public retrieveBookResponse()
        {
        }
        
        public retrieveBookResponse(ServiceReference1.retrieveBookRsp @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.ws/")]
    public partial class retrieveAllBooksRsp
    {
        
        private book[] booksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public book[] books
        {
            get
            {
                return this.booksField;
            }
            set
            {
                this.booksField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retrieveAllBooks", WrapperNamespace="http://soap.ws/", IsWrapped=true)]
    public partial class retrieveAllBooksRequest
    {
        
        public retrieveAllBooksRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retrieveAllBooksResponse", WrapperNamespace="http://soap.ws/", IsWrapped=true)]
    public partial class retrieveAllBooksResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.retrieveAllBooksRsp @return;
        
        public retrieveAllBooksResponse()
        {
        }
        
        public retrieveAllBooksResponse(ServiceReference1.retrieveAllBooksRsp @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.ws/")]
    public partial class updateBookReq
    {
        
        private book bookField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public book book
        {
            get
            {
                return this.bookField;
            }
            set
            {
                this.bookField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateBook", WrapperNamespace="http://soap.ws/", IsWrapped=true)]
    public partial class updateBookRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.updateBookReq arg0;
        
        public updateBookRequest()
        {
        }
        
        public updateBookRequest(ServiceReference1.updateBookReq arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateBookResponse", WrapperNamespace="http://soap.ws/", IsWrapped=true)]
    public partial class updateBookResponse
    {
        
        public updateBookResponse()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface BookWebServiceChannel : ServiceReference1.BookWebService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class BookWebServiceClient : System.ServiceModel.ClientBase<ServiceReference1.BookWebService>, ServiceReference1.BookWebService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BookWebServiceClient() : 
                base(BookWebServiceClient.GetDefaultBinding(), BookWebServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BookWebServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BookWebServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(BookWebServiceClient.GetBindingForEndpoint(endpointConfiguration), BookWebServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BookWebServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BookWebServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BookWebServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BookWebServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BookWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.createBookResponse> ServiceReference1.BookWebService.createBookAsync(ServiceReference1.createBookRequest request)
        {
            return base.Channel.createBookAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.createBookResponse> createBookAsync(ServiceReference1.createBookReq arg0)
        {
            ServiceReference1.createBookRequest inValue = new ServiceReference1.createBookRequest();
            inValue.arg0 = arg0;
            return ((ServiceReference1.BookWebService)(this)).createBookAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.deleteBookResponse> ServiceReference1.BookWebService.deleteBookAsync(ServiceReference1.deleteBookRequest request)
        {
            return base.Channel.deleteBookAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.deleteBookResponse> deleteBookAsync(long arg0)
        {
            ServiceReference1.deleteBookRequest inValue = new ServiceReference1.deleteBookRequest();
            inValue.arg0 = arg0;
            return ((ServiceReference1.BookWebService)(this)).deleteBookAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.retrieveBookResponse> ServiceReference1.BookWebService.retrieveBookAsync(ServiceReference1.retrieveBookRequest request)
        {
            return base.Channel.retrieveBookAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.retrieveBookResponse> retrieveBookAsync(long arg0)
        {
            ServiceReference1.retrieveBookRequest inValue = new ServiceReference1.retrieveBookRequest();
            inValue.arg0 = arg0;
            return ((ServiceReference1.BookWebService)(this)).retrieveBookAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.retrieveAllBooksResponse> ServiceReference1.BookWebService.retrieveAllBooksAsync(ServiceReference1.retrieveAllBooksRequest request)
        {
            return base.Channel.retrieveAllBooksAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.retrieveAllBooksResponse> retrieveAllBooksAsync()
        {
            ServiceReference1.retrieveAllBooksRequest inValue = new ServiceReference1.retrieveAllBooksRequest();
            return ((ServiceReference1.BookWebService)(this)).retrieveAllBooksAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.updateBookResponse> ServiceReference1.BookWebService.updateBookAsync(ServiceReference1.updateBookRequest request)
        {
            return base.Channel.updateBookAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.updateBookResponse> updateBookAsync(ServiceReference1.updateBookReq arg0)
        {
            ServiceReference1.updateBookRequest inValue = new ServiceReference1.updateBookRequest();
            inValue.arg0 = arg0;
            return ((ServiceReference1.BookWebService)(this)).updateBookAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BookWebServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BookWebServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/BookWebService/BookWebService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return BookWebServiceClient.GetBindingForEndpoint(EndpointConfiguration.BookWebServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return BookWebServiceClient.GetEndpointAddress(EndpointConfiguration.BookWebServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            BookWebServicePort,
        }
    }
}
